# Generated by Django 4.0.6 on 2022-07-14 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressBook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressbook',
            old_name='date_created',
            new_name='date_added',
        ),
    ]
